on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      KUBE_NAMESPACE:
        required: true
        type: string
      event_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      registry:
        required: false
        type: string
      aws_region:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # optional
          mask-aws-account-id: 'no'

      - name: Login to registry ${{ inputs.registry }}
        if: inputs.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}/Dockerfile
          push: ${{ inputs.event_name != 'pull_request' }}
          tags: ${{ inputs.registry }}/${{ inputs.IMAGE_NAME }}:${{ inputs.KUBE_NAMESPACE }}
