on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      base_ref:
        required: true
        type: string
    outputs:
      KUBE_NAMESPACE:
        description: "KUBE_NAMESPACE for your branch"
        value: ${{ jobs.init.outputs.k8s_namespace }}

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      k8s_namespace: ${{ steps.setvars.outputs.k8s_namespace }}

    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{ inputs.base_ref }}" == "main" || "${{ inputs.ref }}" == "refs/heads/main" || "${{ inputs.base_ref }}" == "master" || "${{ inputs.ref }}" == "refs/heads/master" ]]; then
            echo "::set-output name=k8s_namespace::prod"
          fi

          if [[ "${{ inputs.base_ref }}" == "development" || "${{ inputs.ref }}" == "refs/heads/development" ]]; then
            echo "::set-output name=k8s_namespace::test"
          fi
