on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      base_ref:
        required: true
        type: string

    outputs:
      KUBE_NAMESPACE:
        value: ${{ jobs.init.outputs.k8s_namespace }}
      ci_env:
        value: ${{ jobs.init.outputs.ci_env }}
      image_name:
        value: ${{ jobs.init.outputs.image_name }}
      registry:
        value: ${{ jobs.init.outputs.registry }}
      aws_region:
        value: ${{ jobs.init.outputs.aws_region }}
      k8s_cluster_name:
        value: ${{ jobs.init.outputs.k8s_cluster_name }}
      app_name:
        value: ${{ jobs.init.outputs.app_name }}
      dockerfile_path:
        value: ${{ jobs.init.outputs.dockerfile_path }}

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      k8s_namespace: ${{ steps.setvars.outputs.k8s_namespace }}
      ci_env: ${{ steps.setvars.outputs.ci_env }}
      image_name: ${{ steps.setvars.outputs.image_name }}
      registry: ${{ steps.setvars.outputs.registry }}
      aws_region: ${{ steps.setvars.outputs.aws_region }}
      k8s_cluster_name: ${{ steps.setvars.outputs.k8s_cluster_name }}
      app_name: ${{ steps.setvars.outputs.app_name }}
      dockerfile_path: ${{ steps.setvars.outputs.dockerfile_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read repo properties
        shell: bash
        run: |
           for i in `cat .github/workflows/ci-properties.json | jq -r 'keys[]'`; do
               if [[ $i != "APP_ENV_VARS" && $i != "DEV_ENV_VARS" && $i != "PROD_ENV_VARS" ]]; then
                   echo "$i=$( cat .github/workflows/ci-properties.json | jq -r .$i)" >> $GITHUB_ENV
               fi
           done;

      - name: Set variables
        id: setvars
        run: |
          if [[ "${{ inputs.base_ref }}" == "${{ env.prod_branch }}" || "${{ inputs.ref }}" == "refs/heads/${{ env.prod_branch }}" ]]; then
            echo "::set-output name=k8s_namespace::production"
            echo "::set-output name=ci_env::PROD"
          fi
          if [[ "${{ inputs.base_ref }}" == "${{ env.dev_branch }}" || "${{ inputs.ref }}" == "refs/heads/${{ env.dev_branch }}" ]]; then
            echo "::set-output name=k8s_namespace::test"
            echo "::set-output name=ci_env::DEV"
          fi
          echo "::set-output name=image_name::${{ env.image_name }}"
          echo "::set-output name=registry::${{ env.registry }}"
          echo "::set-output name=aws_region::${{ env.aws_region }}"
          echo "::set-output name=k8s_cluster_name::${{ env.k8s_cluster_name }}"
          echo "::set-output name=dockerfile_path::${{ env.dockerfile_path }}"
          echo "::set-output name=app_name::${{ env.app_name }}"
